# Generated by Django 4.1.3 on 2022-11-13 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SimStrategy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticker", models.CharField(max_length=10)),
                ("rsi_length", models.IntegerField(blank=True, null=True)),
                ("rsi_high", models.IntegerField(blank=True, null=True)),
                ("rsi_low", models.IntegerField(blank=True, null=True)),
                ("macd_fast", models.IntegerField(blank=True, null=True)),
                ("macd_slow", models.IntegerField(blank=True, null=True)),
                ("ema_length", models.IntegerField(blank=True, null=True)),
                ("trend_line_win", models.IntegerField(blank=True, null=True)),
                ("trend_lever", models.IntegerField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="SimStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.DateTimeField()),
                ("win_ratio", models.DecimalField(decimal_places=2, max_digits=7)),
                ("wins", models.IntegerField(blank=True, null=True)),
                ("losses", models.IntegerField(blank=True, null=True)),
                ("profit", models.DecimalField(decimal_places=10, max_digits=10)),
                (
                    "strategy",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="robot.simstrategy",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SimResults",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("direction", models.IntegerField()),
                ("open_val", models.DecimalField(decimal_places=10, max_digits=10)),
                ("close_val", models.DecimalField(decimal_places=10, max_digits=10)),
                ("win", models.BooleanField(default=False)),
                ("loss", models.BooleanField(default=False)),
                ("date", models.DateTimeField()),
                ("profit", models.DecimalField(decimal_places=10, max_digits=10)),
                (
                    "strategy",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="robot.simstrategy",
                    ),
                ),
            ],
        ),
    ]
